#ifndef CYGONCE_PKGCONF_HAL_MIPS_RA305X_H
#define CYGONCE_PKGCONF_HAL_MIPS_RA305X_H
/*
 * File <pkgconf/hal_mips_ra305x.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGHWR_HAL_MIPS_RA305X_CPU_CLOCK 580000000
#define CYGHWR_HAL_MIPS_RA305X_CPU_CLOCK_580000000
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 2900000
#define CYGNUM_HAL_RTC_PERIOD_2900000
#define CYGNUM_HAL_BREAKPOINT_LIST_SIZE 25
#define CYGNUM_HAL_BREAKPOINT_LIST_SIZE_25
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 3
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_3
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CHANNELS_DEFAULT_BAUD 57600
#define CYGNUM_HAL_VIRTUAL_VECTOR_CHANNELS_DEFAULT_BAUD_57600
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 57600
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_57600
#define CYGHWR_HAL_MIPS_RA305X_FLASH_BASE_ADDR 0xbc000000
#define CYGHWR_HAL_MIPS_RA305X_FLASH_BASE_ADDR_0xbc000000

#endif
