#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL v3_0
#define CYGPKG_HAL_v3_0
#define CYGNUM_HAL_VERSION_MAJOR 3
#define CYGNUM_HAL_VERSION_MINOR 0
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_IO v3_0
#define CYGPKG_IO_v3_0
#define CYGNUM_IO_VERSION_MAJOR 3
#define CYGNUM_IO_VERSION_MINOR 0
#define CYGNUM_IO_VERSION_RELEASE -1
#define CYGPKG_IO_PCI v3_0
#define CYGPKG_IO_PCI_v3_0
#define CYGNUM_IO_PCI_VERSION_MAJOR 3
#define CYGNUM_IO_PCI_VERSION_MINOR 0
#define CYGNUM_IO_PCI_VERSION_RELEASE -1
#define CYGPKG_IO_SERIAL v3_0
#define CYGPKG_IO_SERIAL_v3_0
#define CYGNUM_IO_SERIAL_VERSION_MAJOR 3
#define CYGNUM_IO_SERIAL_VERSION_MINOR 0
#define CYGNUM_IO_SERIAL_VERSION_RELEASE -1
#define CYGPKG_INFRA v3_0
#define CYGPKG_INFRA_v3_0
#define CYGNUM_INFRA_VERSION_MAJOR 3
#define CYGNUM_INFRA_VERSION_MINOR 0
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_KERNEL v3_0
#define CYGPKG_KERNEL_v3_0
#define CYGNUM_KERNEL_VERSION_MAJOR 3
#define CYGNUM_KERNEL_VERSION_MINOR 0
#define CYGNUM_KERNEL_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC v3_0
#define CYGPKG_MEMALLOC_v3_0
#define CYGNUM_MEMALLOC_VERSION_MAJOR 3
#define CYGNUM_MEMALLOC_VERSION_MINOR 0
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA v3_0
#define CYGPKG_ISOINFRA_v3_0
#define CYGNUM_ISOINFRA_VERSION_MAJOR 3
#define CYGNUM_ISOINFRA_VERSION_MINOR 0
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC v3_0
#define CYGPKG_LIBC_v3_0
#define CYGNUM_LIBC_VERSION_MAJOR 3
#define CYGNUM_LIBC_VERSION_MINOR 0
#define CYGNUM_LIBC_VERSION_RELEASE -1
#define CYGPKG_LIBC_I18N v3_0
#define CYGPKG_LIBC_I18N_v3_0
#define CYGNUM_LIBC_I18N_VERSION_MAJOR 3
#define CYGNUM_LIBC_I18N_VERSION_MINOR 0
#define CYGNUM_LIBC_I18N_VERSION_RELEASE -1
#define CYGPKG_LIBC_SETJMP v3_0
#define CYGPKG_LIBC_SETJMP_v3_0
#define CYGNUM_LIBC_SETJMP_VERSION_MAJOR 3
#define CYGNUM_LIBC_SETJMP_VERSION_MINOR 0
#define CYGNUM_LIBC_SETJMP_VERSION_RELEASE -1
#define CYGPKG_LIBC_SIGNALS v3_0
#define CYGPKG_LIBC_SIGNALS_v3_0
#define CYGNUM_LIBC_SIGNALS_VERSION_MAJOR 3
#define CYGNUM_LIBC_SIGNALS_VERSION_MINOR 0
#define CYGNUM_LIBC_SIGNALS_VERSION_RELEASE -1
#define CYGPKG_LIBC_STARTUP v3_0
#define CYGPKG_LIBC_STARTUP_v3_0
#define CYGNUM_LIBC_STARTUP_VERSION_MAJOR 3
#define CYGNUM_LIBC_STARTUP_VERSION_MINOR 0
#define CYGNUM_LIBC_STARTUP_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDIO v3_0
#define CYGPKG_LIBC_STDIO_v3_0
#define CYGNUM_LIBC_STDIO_VERSION_MAJOR 3
#define CYGNUM_LIBC_STDIO_VERSION_MINOR 0
#define CYGNUM_LIBC_STDIO_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDLIB v3_0
#define CYGPKG_LIBC_STDLIB_v3_0
#define CYGNUM_LIBC_STDLIB_VERSION_MAJOR 3
#define CYGNUM_LIBC_STDLIB_VERSION_MINOR 0
#define CYGNUM_LIBC_STDLIB_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING v3_0
#define CYGPKG_LIBC_STRING_v3_0
#define CYGNUM_LIBC_STRING_VERSION_MAJOR 3
#define CYGNUM_LIBC_STRING_VERSION_MINOR 0
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_LIBC_TIME v3_0
#define CYGPKG_LIBC_TIME_v3_0
#define CYGNUM_LIBC_TIME_VERSION_MAJOR 3
#define CYGNUM_LIBC_TIME_VERSION_MINOR 0
#define CYGNUM_LIBC_TIME_VERSION_RELEASE -1
#define CYGPKG_LIBM v3_0
#define CYGPKG_LIBM_v3_0
#define CYGNUM_LIBM_VERSION_MAJOR 3
#define CYGNUM_LIBM_VERSION_MINOR 0
#define CYGNUM_LIBM_VERSION_RELEASE -1
#define CYGPKG_IO_WALLCLOCK v3_0
#define CYGPKG_IO_WALLCLOCK_v3_0
#define CYGNUM_IO_WALLCLOCK_VERSION_MAJOR 3
#define CYGNUM_IO_WALLCLOCK_VERSION_MINOR 0
#define CYGNUM_IO_WALLCLOCK_VERSION_RELEASE -1
#define CYGPKG_ERROR v3_0
#define CYGPKG_ERROR_v3_0
#define CYGNUM_ERROR_VERSION_MAJOR 3
#define CYGNUM_ERROR_VERSION_MINOR 0
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_IO_FILEIO v3_0
#define CYGPKG_IO_FILEIO_v3_0
#define CYGNUM_IO_FILEIO_VERSION_MAJOR 3
#define CYGNUM_IO_FILEIO_VERSION_MINOR 0
#define CYGNUM_IO_FILEIO_VERSION_RELEASE -1
#define CYGPKG_HAL_MIPS v3_0
#define CYGPKG_HAL_MIPS_v3_0
#define CYGNUM_HAL_MIPS_VERSION_MAJOR 3
#define CYGNUM_HAL_MIPS_VERSION_MINOR 0
#define CYGNUM_HAL_MIPS_VERSION_RELEASE -1
#define CYGPKG_HAL_MIPS_MIPS32 v3_0
#define CYGPKG_HAL_MIPS_MIPS32_v3_0
#define CYGNUM_HAL_MIPS_MIPS32_VERSION_MAJOR 3
#define CYGNUM_HAL_MIPS_MIPS32_VERSION_MINOR 0
#define CYGNUM_HAL_MIPS_MIPS32_VERSION_RELEASE -1
#define CYGPKG_HAL_MIPS_RA305X v3_0
#define CYGPKG_HAL_MIPS_RA305X_v3_0
#define CYGNUM_HAL_MIPS_RA305X_VERSION_MAJOR 3
#define CYGNUM_HAL_MIPS_RA305X_VERSION_MINOR 0
#define CYGNUM_HAL_MIPS_RA305X_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H <pkgconf/hal_mips_mips32.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_mips_ra305x.h>

/* Make sure we get the CORE type definitions for HAL_PLATFORM_CPU */
#include CYGBLD_HAL_TARGET_H
#define HAL_PLATFORM_BOARD    "RALINK_RA305X"
#define HAL_PLATFORM_EXTRA    ""

#  define HAL_PLATFORM_CPU    "MIPS32 24Kc"

#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_mips_ra305x_ram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_mips_ra305x_ram.h>
#define CYGPKG_IO_SERIAL_MIPS_RA305X v3_0
#define CYGPKG_IO_SERIAL_MIPS_RA305X_v3_0
#define CYGNUM_IO_SERIAL_MIPS_RA305X_VERSION_MAJOR 3
#define CYGNUM_IO_SERIAL_MIPS_RA305X_VERSION_MINOR 0
#define CYGNUM_IO_SERIAL_MIPS_RA305X_VERSION_RELEASE -1
/***** serial driver proc output start *****/
#define CYGDAT_IO_SERIAL_DEVICE_HEADER <pkgconf/io_serial_mips_ra305x.h>
/*****  serial driver proc output end  *****/
#define CYGPKG_DEVS_FLASH_SPI_MX25LXXX v3_0
#define CYGPKG_DEVS_FLASH_SPI_MX25LXXX_v3_0
#define CYGNUM_DEVS_FLASH_SPI_MX25LXXX_VERSION_MAJOR 3
#define CYGNUM_DEVS_FLASH_SPI_MX25LXXX_VERSION_MINOR 0
#define CYGNUM_DEVS_FLASH_SPI_MX25LXXX_VERSION_RELEASE -1
#define CYGPKG_IO_ETH_DRIVERS v3_0
#define CYGPKG_IO_ETH_DRIVERS_v3_0
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MAJOR 3
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MINOR 0
#define CYGNUM_IO_ETH_DRIVERS_VERSION_RELEASE -1
#define CYGPKG_IO_FLASH v3_0
#define CYGPKG_IO_FLASH_v3_0
#define CYGNUM_IO_FLASH_VERSION_MAJOR 3
#define CYGNUM_IO_FLASH_VERSION_MINOR 0
#define CYGNUM_IO_FLASH_VERSION_RELEASE -1
#define CYGPKG_IO_DISK v3_0
#define CYGPKG_IO_DISK_v3_0
#define CYGNUM_IO_DISK_VERSION_MAJOR 3
#define CYGNUM_IO_DISK_VERSION_MINOR 0
#define CYGNUM_IO_DISK_VERSION_RELEASE -1
#define CYGPKG_LINUX_COMPAT v3_0
#define CYGPKG_LINUX_COMPAT_v3_0
#define CYGNUM_LINUX_COMPAT_VERSION_MAJOR 3
#define CYGNUM_LINUX_COMPAT_VERSION_MINOR 0
#define CYGNUM_LINUX_COMPAT_VERSION_RELEASE -1
#define CYGPKG_BLOCK_LIB v3_0
#define CYGPKG_BLOCK_LIB_v3_0
#define CYGNUM_BLOCK_LIB_VERSION_MAJOR 3
#define CYGNUM_BLOCK_LIB_VERSION_MINOR 0
#define CYGNUM_BLOCK_LIB_VERSION_RELEASE -1

#endif
