#ifndef UART_CMD_MISC_H
#define UART_CMD_MISC_H

void cmd_deal_wsssid(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_webu(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wmode(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wap(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wmac(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_nmac(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_lmac(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_h(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_security(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_mid(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wtmid(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_freq(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_z(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_mslp(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wslk(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wslq(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_eep(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_ated(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_ephy(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_ver(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_reld(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_eptp(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_lver(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tcpto(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tcplk(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_udat(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_telnetd(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tmode(char *cmd_line, int len, int op_code, int para_pos, char *rep);
//void cmd_deal_alc(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fakey(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fskey(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fassid(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fver(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fbgn(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wsssid1(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wsssid2(char *cmd_line, int len, int op_code, int para_pos, char *rep);
//void cmd_deal_walk(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fclr(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fhelp(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fnrdy(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_maxsk(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fsssid(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_uartf(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_uartft(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_uartfl(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_flogo(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fmaxsk(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fephy(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_feptp(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fwmode(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_ftmode(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_flang(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fwebu(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_faenc(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fsenc(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_ftcpto(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_faft(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fafl(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tcpdis(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tcpb(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tcptob(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tcpptb(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tcpaddb(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_tcplkb(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fwupdat(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fvmen(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_faswd(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_ping(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_wtpwr(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fapsta(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_stach(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fvew(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_fsttc(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void cmd_deal_sttc(char *cmd_line, int len, int op_code, int para_pos, char *rep);
void str_escape(char *src);
int str2hex(char *str);

#endif

